### ISSUE TITLE
Issue in v3.0 

### ISSUE THREAD

**Issue by twlworker-us-5** [microsoftgraph/aspnet-security-api-sample#31]
Heads up, I get the error below when running v3.0

       app.Run(async (context) =>
            {
                context.Response.ContentType = "text/html";
                await context.Response.SendFileAsync(Path.Combine(env.WebRootPath, "index.html"));
            });

Error: 

System.ArgumentNullException: Value cannot be null.

Parameter name: path1

   at System.IO.Path.Combine(String path1, String path2)

   at MicrosoftGraph_Security_API_Sample.Startup.<>c__DisplayClass5_0.<<Configure>b__4>d.MoveNext() in Z:\d\aspnet-security-api-sample\V3.0\MicrosoftGraph_Security_API_Sample\Startup.cs:line 180

--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)

   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)

   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)

   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)

   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)

   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)

   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by twlworker-us-5** [comment]
Also, to get v2.0 to work, I had to remove all the roslyn csc directives inside the .csproj

**Comment by Mounika-Chillamcherla** [comment]
This issue is because of the Visual studio setting. Can you follow the **"Visual Studio Settings"** [here](https://github.com/microsoftgraph/aspnet-security-api-sample/tree/master/V3.0#build-and-run-the-sample)  and see if it works.

**Comment by foppenm** [comment]
> This issue is because of the Visual studio setting. Can you follow the **"Visual Studio Settings"** [here](https://github.com/microsoftgraph/aspnet-security-api-sample/tree/master/V3.0#build-and-run-the-sample) and see if it works.

This fixed it for me. Especially the part "Launch Browser: swagger" which I overlooked.
